In [22]:
import pandas as pd
import requests

# Default

In [23]:
actual_data_url="https://data.elexon.co.uk/bmrs/api/v1/datasets/FUELHH/stream"

In [24]:
df=pd.read_json(actual_data_url)
df

,dataset,publishTime,startTime,settlementDate,settlementPeriod,fuelType,generation
0,FUELHH,2026-10-28T10:00:00Z,2026-10-28T09:30:00Z,2026-10-28,20,BIOMASS,3097
1,FUELHH,2026-10-28T10:00:00Z,2026-10-28T09:30:00Z,2026-10-28,20,CCGT,5634
2,FUELHH,2026-10-28T10:00:00Z,2026-10-28T09:30:00Z,2026-10-28,20,COAL,0
3,FUELHH,2026-10-28T10:00:00Z,2026-10-28T09:30:00Z,2026-10-28,20,INTELEC,168
4,FUELHH,2026-10-28T10:00:00Z,2026-10-28T09:30:00Z,2026-10-28,20,INTEW,0
...,...,...,...,...,...,...,...
395,FUELHH,2026-10-28T00:30:00Z,2026-10-28T00:00:00Z,2026-10-28,1,OCGT,2
396,FUELHH,2026-10-28T00:30:00Z,2026-10-28T00:00:00Z,2026-10-28,1,OIL,0
397,FUELHH,2026-10-28T00:30:00Z,2026-10-28T00:00:00Z,2026-10-28,1,OTHER,718
398,FUELHH,2026-10-28T00:30:00Z,2026-10-28T00:00:00Z,2026-10-28,1,PS,-798
399,FUELHH,2026-10-28T00:30:00Z,2026-10-28T00:00:00Z,2026-10-28,1,WIND,11533

In [25]:
df.to_csv("original_data.csv",index=False)

In [26]:
forecast_url="https://data.elexon.co.uk/bmrs/api/v1/datasets/WINDFOR/stream"
df=pd.read_json(forecast_url)
df

    dataset           publishTime             startTime  generation
0   WINDFOR  2026-10-28T09:30:00Z  2026-10-27T21:00:00Z       19916
1   WINDFOR  2026-10-28T09:30:00Z  2026-10-27T22:00:00Z       19599
2   WINDFOR  2026-10-28T09:30:00Z  2026-10-27T23:00:00Z       19449
3   WINDFOR  2026-10-28T09:30:00Z  2026-10-28T00:00:00Z       19102
4   WINDFOR  2026-10-28T09:30:00Z  2026-10-28T01:00:00Z       19017
..      ...                   ...                   ...         ...
68  WINDFOR  2026-10-28T09:30:00Z  2026-10-30T17:00:00Z        7189
69  WINDFOR  2026-10-28T09:30:00Z  2026-10-30T18:00:00Z        7185
70  WINDFOR  2026-10-28T09:30:00Z  2026-10-30T19:00:00Z        6943
71  WINDFOR  2026-10-28T09:30:00Z  2026-10-30T20:00:00Z        6510
72  WINDFOR  2026-10-28T09:30:00Z  2026-10-30T21:00:00Z        5961

[73 rows x 4 columns]

In [27]:
df.to_csv("forecast.csv",index=False)

# Custom

In [28]:
# 15 January 2026 ka Actual Data
actual_test_url = "https://data.elexon.co.uk/bmrs/api/v1/datasets/FUELHH/stream?publishDateTimeFrom=2026-01-15T00:00:00Z&publishDateTimeTo=2026-01-15T23:59:59Z"

df_actual = pd.read_json(actual_test_url)

# Sirf WIND wala filter karke check karo
df_wind_actual = df_actual[df_actual['fuelType'] == 'WIND']
print("Actual Wind Rows:", len(df_wind_actual))
df_wind_actual.head()

Actual Wind Rows: 48

,dataset,publishTime,startTime,settlementDate,settlementPeriod,fuelType,generation
19,FUELHH,2026-01-15T23:30:00Z,2026-01-15T23:00:00Z,2026-01-15,47,WIND,7258
39,FUELHH,2026-01-15T23:00:00Z,2026-01-15T22:30:00Z,2026-01-15,46,WIND,7431
59,FUELHH,2026-01-15T22:30:00Z,2026-01-15T22:00:00Z,2026-01-15,45,WIND,7685
79,FUELHH,2026-01-15T22:00:00Z,2026-01-15T21:30:00Z,2026-01-15,44,WIND,7964
99,FUELHH,2026-01-15T21:30:00Z,2026-01-15T21:00:00Z,2026-01-15,43,WIND,7603

In [29]:
# 15 January 2026 ka Forecast Data
forecast_test_url = "https://data.elexon.co.uk/bmrs/api/v1/datasets/WINDFOR/stream?publishDateTimeFrom=2026-01-14T00:00:00Z&publishDateTimeTo=2026-01-15T00:00:00Z"

df_forecast = pd.read_json(forecast_test_url)
print("Forecast Rows:", len(df_forecast))
df_forecast.head()

Forecast Rows: 584

   dataset           publishTime             startTime  generation
0  WINDFOR  2026-01-14T22:30:00Z  2026-01-13T21:00:00Z       12079
1  WINDFOR  2026-01-14T22:30:00Z  2026-01-13T22:00:00Z       11434
2  WINDFOR  2026-01-14T22:30:00Z  2026-01-13T23:00:00Z       10988
3  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T00:00:00Z       10739
4  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T01:00:00Z       10702

In [30]:
df_forecast.head(30)

    dataset           publishTime             startTime  generation
0   WINDFOR  2026-01-14T22:30:00Z  2026-01-13T21:00:00Z       12079
1   WINDFOR  2026-01-14T22:30:00Z  2026-01-13T22:00:00Z       11434
2   WINDFOR  2026-01-14T22:30:00Z  2026-01-13T23:00:00Z       10988
3   WINDFOR  2026-01-14T22:30:00Z  2026-01-14T00:00:00Z       10739
4   WINDFOR  2026-01-14T22:30:00Z  2026-01-14T01:00:00Z       10702
5   WINDFOR  2026-01-14T22:30:00Z  2026-01-14T02:00:00Z       10218
6   WINDFOR  2026-01-14T22:30:00Z  2026-01-14T03:00:00Z        9645
7   WINDFOR  2026-01-14T22:30:00Z  2026-01-14T04:00:00Z        9233
8   WINDFOR  2026-01-14T22:30:00Z  2026-01-14T05:00:00Z        8822
9   WINDFOR  2026-01-14T22:30:00Z  2026-01-14T06:00:00Z        8445
10  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T07:00:00Z        8117
11  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T08:00:00Z        7853
12  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T09:00:00Z        7830
13  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T10:00:00Z        7901
14  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T11:00:00Z        8035
15  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T12:00:00Z        8150
16  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T13:00:00Z        8395
17  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T14:00:00Z        9139
18  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T15:00:00Z        9561
19  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T16:00:00Z       10271
20  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T17:00:00Z       11380
21  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T18:00:00Z       12691
22  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T19:00:00Z       14368
23  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T20:00:00Z       15684
24  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T21:00:00Z       16732
25  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T22:00:00Z       17022
26  WINDFOR  2026-01-14T22:30:00Z  2026-01-14T23:00:00Z       16912
27  WINDFOR  2026-01-14T22:30:00Z  2026-01-15T00:00:00Z       16500
28  WINDFOR  2026-01-14T22:30:00Z  2026-01-15T01:00:00Z       16110
29  WINDFOR  2026-01-14T22:30:00Z  2026-01-15T02:00:00Z       15592

In [31]:
df_forecast.tail()

     dataset           publishTime             startTime  generation
579  WINDFOR  2026-01-14T02:30:00Z  2026-01-16T17:00:00Z        7924
580  WINDFOR  2026-01-14T02:30:00Z  2026-01-16T18:00:00Z        7892
581  WINDFOR  2026-01-14T02:30:00Z  2026-01-16T19:00:00Z        7777
582  WINDFOR  2026-01-14T02:30:00Z  2026-01-16T20:00:00Z        7568
583  WINDFOR  2026-01-14T02:30:00Z  2026-01-16T21:00:00Z        7268

In [32]:
# Dekho ki 15 Jan ke liye kaun-kaun se forecasts hain
x=df_forecast[df_forecast['startTime'].str.startswith('2026-01-15')].head(192)
x

     dataset           publishTime             startTime  generation
27   WINDFOR  2026-01-14T22:30:00Z  2026-01-15T00:00:00Z       16500
28   WINDFOR  2026-01-14T22:30:00Z  2026-01-15T01:00:00Z       16110
29   WINDFOR  2026-01-14T22:30:00Z  2026-01-15T02:00:00Z       15592
30   WINDFOR  2026-01-14T22:30:00Z  2026-01-15T03:00:00Z       15121
31   WINDFOR  2026-01-14T22:30:00Z  2026-01-15T04:00:00Z       14860
..       ...                   ...                   ...         ...
557  WINDFOR  2026-01-14T02:30:00Z  2026-01-15T19:00:00Z        9130
558  WINDFOR  2026-01-14T02:30:00Z  2026-01-15T20:00:00Z        9059
559  WINDFOR  2026-01-14T02:30:00Z  2026-01-15T21:00:00Z        9049
560  WINDFOR  2026-01-14T02:30:00Z  2026-01-15T22:00:00Z        9091
561  WINDFOR  2026-01-14T02:30:00Z  2026-01-15T23:00:00Z        8966

[192 rows x 4 columns]

In [33]:
len(x)

192

In [34]:
test_date = "2026-10-27"
# 1. October 27 Actuals fetch karo
actual_url = f"https://data.elexon.co.uk/bmrs/api/v1/datasets/FUELHH/stream?publishDateTimeFrom={test_date}T00:00:00Z&publishDateTimeTo={test_date}T23:59:59Z"
df_act = pd.read_json(actual_url)
df_wind = df_act[df_act['fuelType'] == 'WIND']

In [35]:
forecast_url = "https://data.elexon.co.uk/bmrs/api/v1/datasets/WINDFOR/stream?publishDateTimeFrom=2026-10-26T00:00:00Z&publishDateTimeTo=2026-10-27T00:00:00Z"
df_fc = pd.read_json(forecast_url)
df_target_fc = df_fc[df_fc['startTime'].str.startswith(test_date)]
print(f"[{test_date}] Actual Wind Rows:", len(df_wind))
print(f"[{test_date}] Day-Ahead Forecast Rows:", len(df_target_fc))
df_wind[['settlementPeriod', 'startTime', 'generation']].head()

[2026-10-27] Actual Wind Rows: 48
[2026-10-27] Day-Ahead Forecast Rows: 192

    settlementPeriod             startTime  generation
19                47  2026-10-27T23:00:00Z       12568
39                46  2026-10-27T22:30:00Z       12973
59                45  2026-10-27T22:00:00Z       13129
79                44  2026-10-27T21:30:00Z       13457
99                43  2026-10-27T21:00:00Z       13523